### ISSUE TITLE
Interaction with git-gone and the push.default git config? 

### ISSUE THREAD

**Issue by bgianfo** [lunaryorn/git-gone#11]
git-gone has stopped working for most of my PR's, I'm wondering if there is some behavior with the push.default git config?
https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault

My hypothesis is that maybe git doesn't actually set the upstream in the metadata if the push.default config is set to current. Maybe it just infers it on the fly, so there is no metadata about it for git-gone to read? 

    C:\src> git config --get push.default
    current

**Comment by lunaryorn** [comment]
Isn't the whole purpose of `current` to push without having upstream set?  As far as I understand its description it just pushes to a remote branch of the same name, so you'd never have upstream for your own branches.  If that's not what you like why set `push.default` to `current` at all?

In any case git-gone needs upstream, and without upstream it's impossible to make git-gone work, as far as I can see: An upstream is all that distinguishes between a local branch that was pushed but then deleted on the remote from a local branch that was never pushed, so I don't think you can safely clean local branches in any other way.

I'll close this issue:  If you'd like to use git without upstream then git-gone just isn't the tool for you :)

**Comment by bgianfo** [comment]
Thanks for the confirmation, that's all I wanted...

**Comment by lunaryorn** [comment]
You're welcome
