### ISSUE TITLE
cargo install consistently fails with: no targets specified in the manifest

### ISSUE THREAD

**Issue by bgianfo** [lunaryorn/git-gone#12]
I haven't been able to install git-gone using cargo install since v0.3.0.
I get the following error on all point releases since: 
```
error: failed to download `git-gone v0.3.6`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\<User>\.cargo\registry\src\github.com-1ecc6299db9ec823\git-gone-0.3.6\Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

Cargo version: 
```
C:\>cargo version
cargo 1.44.1 (88ba85757 2020-06-11)
```

**Comment by lunaryorn** [comment]
I don't understand why this broke all of a sudden.  `src/main.rs` exists, so why the error message?  Is this caused by a change in git-gone or by a change in Cargo?

**Comment by bgianfo** [comment]
After digging around some more I think it was actually this change 2881d30e26d40f93e435d59385b378b105aeb4e0.

If I look at the directories after cargo downloads them the new versions are virtually empty, while as the old directories contain all contents.

```
$ tree /F git-gone-0.3.0
Folder PATH listing for volume Windows
Volume serial number is BEAD-E2D6
C:\USERS\<User>\.CARGO\REGISTRY\SRC\GITHUB.COM-1ECC6299DB9EC823\GIT-GONE-0.3.0
│   .cargo-ok
│   .cargo_vcs_info.json
│   .gitignore
│   Cargo.lock
│   Cargo.toml
│   Cargo.toml.orig
│   CHANGELOG.md
│   LICENSE
│   README.md
│
├───.github
│   └───workflows
│           ci.yml
│           release.yml
│
├───scripts
│       release
│
└───src
        main.rs

$ tree /F git-gone-0.3.6
Folder PATH listing for volume Windows
Volume serial number is BEAD-E2D6
C:\USERS\<USER>\.CARGO\REGISTRY\SRC\GITHUB.COM-1ECC6299DB9EC823\GIT-GONE-0.3.6
    .cargo-ok
    .cargo_vcs_info.json
    Cargo.lock
    Cargo.toml
    Cargo.toml.orig
    git-gone.1
    git-gone.1.adoc

No subfolders exist
```

**Comment by lunaryorn** [comment]
@bgianfo Oh, that's stupid :pensive:  I've added the missing files to `include`; I'll make a new release soon, and yank the broken versions from crates.io.

0.3.0 is the first broken version?

**Comment by bgianfo** [comment]
I think 0.3.1 is the first broken version.

**Comment by lunaryorn** [comment]
Yanked the broken ones and pushed 0.3.7

**Comment by bgianfo** [comment]
Validated cargo install works again with 0.3.7, thanks!

**Comment by lunaryorn** [comment]
You're welcome.  By the way I'm just curious why you don't use the prebuilt release binary?

**Comment by bgianfo** [comment]
I've had my setup of cargo install, then using cargo install-outdated -all or [topgrade](https://github.com/r-darwish/topgrade) to keep packages updated for a while, long before you provided prebuilt release binaries.

Today I use [scoop](https://github.com/lukesampson/scoop) as my package manager on windows, so I would have to write a scoop manifest to automatically consume your github releases, which isn't very complicated ([example](https://github.com/ScoopInstaller/Main/pull/1256/files)), I just haven't ever gotten around to doing it.

**Comment by lunaryorn** [comment]
I see. Thanks for explaining 🙏
